[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/disc"
  to = "/disc.html"
  status = 200

[[redirects]]
  from = "/informe"
  to = "/informe.html"
  status = 200
